import { Armor, ArmorCategory } from '../../types/armor';
import { ElementType } from '../../types/element';

export const CHESTPLATES: Armor[] = [
  {
    id: 55,
    name: 'Haillon',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [
      { stat: 'resistance', bonus: 1 },
      { stat: 'armor', bonus: 1 },
    ],
    rank: 0,
    weight: 1,
  },
  {
    id: 48,
    name: 'Armure en cuir',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [
      { stat: 'armor', bonus: 2 },
      { stat: 'resistance', bonus: 2 },
    ],
    rank: 1,
    weight: 2,
  },
  {
    id: 78,
    name: 'Plastron',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [{ stat: 'armor', bonus: 4 }],
    rank: 1,
    weight: 3,
  },
  {
    id: 18,
    name: 'Toge',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [{ stat: 'resistance', bonus: 4 }],
    rank: 1,
    weight: 1,
  },
  {
    id: 124,
    name: 'Veston',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [
      { stat: 'armor', bonus: 1 },
      { stat: 'resistance', bonus: 1 },
      { stat: 'stealth', bonus: 10 },
    ],
    rank: 1,
    weight: 1,
  },
  {
    id: 74,
    name: 'Brigandine',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [
      { stat: 'armor', bonus: 3 },
      { stat: 'resistance', bonus: 3 },
    ],
    rank: 2,
    weight: 2,
  },
  {
    id: 9,
    name: 'Cotte de mailles',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [{ stat: 'armor', bonus: 6 }],
    rank: 2,
    weight: 4,
  },
  {
    id: 198,
    name: 'Fourrure',
    category: ArmorCategory.CHESTPLATE,
    resistances: [
      { element: ElementType.FIRE, percentage: 10 },
      { element: ElementType.ICE, percentage: 10 },
      { element: ElementType.THUNDER, percentage: 10 },
    ],
    bonuses: [
      { stat: 'armor', bonus: 2 },
      { stat: 'resistance', bonus: 2 },
    ],
    rank: 2,
    weight: 3,
  },
  {
    id: 184,
    name: 'Pèlerine',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [
      { stat: 'stealth', bonus: 10 },
      { stat: 'evasion', bonus: 10 },
      { stat: 'magicDefense', bonus: 10 },
    ],
    rank: 2,
    weight: 2,
  },
  {
    id: 92,
    name: 'Toge en soie',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [{ stat: 'resistance', bonus: 6 }],
    rank: 2,
    weight: 2,
  },
  {
    id: 87,
    name: 'Armure astrale',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [
      { stat: 'armor', bonus: 6 },
      { stat: 'dexterity', bonus: 2 },
    ],
    rank: 3,
    weight: 3,
  },
  {
    id: 82,
    name: 'Armure de plates',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [{ stat: 'armor', bonus: 8 }],
    rank: 3,
    weight: 3,
  },
  {
    id: 191,
    name: 'Bliaut',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [
      { stat: 'damage', bonus: 2 },
      { stat: 'evasion', bonus: 10 },
      { stat: 'magicDefense', bonus: 10 },
      { stat: 'stealth', bonus: 10 },
    ],
    rank: 3,
    weight: 2,
  },
  {
    id: 111,
    name: 'Cape',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [
      { stat: 'evasion', bonus: 15 },
      { stat: 'charisma', bonus: 2 },
      { stat: 'magicDefense', bonus: 15 },
    ],
    rank: 3,
    weight: 1,
  },
  {
    id: 106,
    name: 'Ceinture de force',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [
      { stat: 'armor', bonus: 2 },
      { stat: 'resistance', bonus: 2 },
      { stat: 'strength', bonus: 2 },
      { stat: 'evasion', bonus: 10 },
    ],
    rank: 3,
    weight: 1,
  },
  {
    id: 81,
    name: 'Cuirasse',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [
      { stat: 'armor', bonus: 6 },
      { stat: 'damage', bonus: 2 },
    ],
    rank: 3,
    weight: 3,
  },
  {
    id: 232,
    name: 'Dérobade en soie',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [
      { stat: 'resistance', bonus: 6 },
      { stat: 'magicMastery', bonus: 10 },
    ],
    rank: 3,
    weight: 1,
  },
  {
    id: 313,
    name: 'Harlequine',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [
      { stat: 'armor', bonus: 3 },
      { stat: 'resistance', bonus: 3 },
      { stat: 'magicMastery', bonus: 10 },
    ],
    rank: 3,
    weight: 3,
  },
  {
    id: 161,
    name: 'Kimono',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [
      { stat: 'armor', bonus: 3 },
      { stat: 'resistance', bonus: 3 },
      { stat: 'evasion', bonus: 10 },
    ],
    rank: 3,
    weight: 2,
  },
  {
    id: 318,
    name: 'Manteau de rôdeur',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [
      { stat: 'dexterity', bonus: 2 },
      { stat: 'evasion', bonus: 15 },
      { stat: 'stealth', bonus: 15 },
    ],
    rank: 3,
    weight: 2,
  },
  {
    id: 334,
    name: 'Manteau du nomade',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [
      { stat: 'luck', bonus: 100 },
      { stat: 'magicDefense', bonus: 10 },
      { stat: 'evasion', bonus: 10 },
    ],
    rank: 3,
    weight: 3,
  },
  {
    id: 21,
    name: 'Pèlerine en soie',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [
      { stat: 'stealth', bonus: 10 },
      { stat: 'evasion', bonus: 15 },
      { stat: 'magicDefense', bonus: 15 },
    ],
    rank: 3,
    weight: 2,
  },
  {
    id: 192,
    name: 'Plastron miroir',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [
      { stat: 'armor', bonus: 5 },
      { stat: 'magicDefense', bonus: 15 },
    ],
    rank: 3,
    weight: 3,
  },
  {
    id: 354,
    name: 'Armure de la fournaise',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [{ stat: 'armor', bonus: 7 }],
    resistances: [{ element: ElementType.FIRE, percentage: 20 }],
    rank: 3,
    weight: 3,
  },
  {
    id: 236,
    name: 'Cotte de mailles en mithril',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [{ stat: 'armor', bonus: 7 }],
    extraGem: true,
    rank: 3,
    weight: 3,
  },
  {
    id: 193,
    name: 'Plastron dragon',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [
      { stat: 'magicMastery', bonus: 10 },
      { stat: 'armor', bonus: 6 },
    ],
    rank: 3,
    weight: 3,
  },
  {
    id: 31,
    name: 'Plastron noble',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [
      { stat: 'armor', bonus: 6 },
      { stat: 'intelligence', bonus: 2 },
    ],
    rank: 3,
    weight: 3,
  },
  {
    id: 197,
    name: 'Plastron terrifiant',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [
      { stat: 'armor', bonus: 6 },
      { stat: 'strength', bonus: 2 },
    ],
    rank: 3,
    weight: 3,
  },
  {
    id: 129,
    name: 'Tenue améthyste',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [
      { stat: 'resistance', bonus: 6 },
      { stat: 'magicDamage', bonus: 2 },
    ],
    rank: 3,
    weight: 2,
  },
  {
    id: 307,
    name: "Tunique de l'ombre",
    category: ArmorCategory.CHESTPLATE,
    bonuses: [
      { stat: 'precision', bonus: 10 },
      { stat: 'evasion', bonus: 15 },
      { stat: 'stealth', bonus: 15 },
    ],
    rank: 3,
    weight: 2,
  },
  {
    id: 58,
    name: 'Tunique en soie',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [
      { stat: 'evasion', bonus: 15 },
      { stat: 'magicDefense', bonus: 15 },
      { stat: 'intelligence', bonus: 2 },
    ],
    rank: 3,
    weight: 2,
  },
  {
    id: 360,
    name: 'Robe des ténèbres',
    category: ArmorCategory.CHESTPLATE,
    bonuses: [
      { stat: 'resistance', bonus: 5 },
      { stat: 'stealth', bonus: 10 },
    ],
    resistances: [{ element: ElementType.DARK, percentage: 20 }],
    rank: 3,
    weight: 3,
  },
];
