import { Armor, ArmorCategory } from '../../types/armor';
import { ElementType } from '../../types/element';

export const HELMETS: Armor[] = [
  {
    id: 59,
    name: 'Bandana',
    category: ArmorCategory.HELMET,
    bonuses: [{ stat: 'evasion', bonus: 10 }],
    rank: 1,
    weight: 1,
  },
  {
    id: 7,
    name: 'Cabasset en cuivre',
    category: ArmorCategory.HELMET,
    bonuses: [{ stat: 'armor', bonus: 2 }],
    rank: 1,
    weight: 1,
  },
  {
    id: 285,
    name: 'Casque en bois',
    category: ArmorCategory.HELMET,
    bonuses: [{ stat: 'armor', bonus: 2 }],
    rank: 1,
    weight: 1,
  },
  {
    id: 361,
    name: 'Masque des ténèbres',
    category: ArmorCategory.HELMET,
    bonuses: [
      { stat: 'resistance', bonus: 2 },
      { stat: 'magicDamage', bonus: 1 },
    ],
    resistances: [{ element: ElementType.DARK, percentage: 20 }],
    rank: 1,
    weight: 2,
  },
  {
    id: 166,
    name: 'Capuchon',
    category: ArmorCategory.HELMET,
    bonuses: [{ stat: 'resistance', bonus: 2 }],
    rank: 1,
    weight: 1,
  },
  {
    id: 19,
    name: 'Toque',
    category: ArmorCategory.HELMET,
    bonuses: [
      { stat: 'armor', bonus: 1 },
      { stat: 'resistance', bonus: 1 },
    ],
    rank: 1,
    weight: 1,
  },
  {
    id: 32,
    name: 'Casque',
    category: ArmorCategory.HELMET,
    bonuses: [{ stat: 'armor', bonus: 3 }],
    rank: 2,
    weight: 2,
  },
  {
    id: 439,
    name: 'Capuche de voleur',
    category: ArmorCategory.HELMET,
    bonuses: [{ stat: 'stealth', bonus: 15 }],
    rank: 2,
    weight: 1,
  },
  {
    id: 440,
    name: "Lunettes d'explorateur",
    category: ArmorCategory.HELMET,
    bonuses: [{ stat: 'observation', bonus: 15 }],
    rank: 2,
    weight: 1,
  },
  {
    id: 146,
    name: 'Bandana en soie',
    category: ArmorCategory.HELMET,
    bonuses: [
      { stat: 'evasion', bonus: 10 },
      { stat: 'magicDefense', bonus: 10 },
    ],
    rank: 3,
    weight: 1,
  },
  {
    id: 286,
    name: 'Barrette en or',
    category: ArmorCategory.HELMET,
    extraGem: true,
    bonuses: [{ stat: 'magicDefense', bonus: 15 }],
    rank: 3,
    weight: 1,
  },
  {
    id: 233,
    name: 'Bassinet plume',
    category: ArmorCategory.HELMET,
    bonuses: [
      { stat: 'armor', bonus: 3 },
      { stat: 'precision', bonus: 5 },
    ],
    rank: 3,
    weight: 2,
  },
  {
    id: 121,
    name: 'Bonnet émeraude',
    category: ArmorCategory.HELMET,
    bonuses: [
      { stat: 'intelligence', bonus: 1 },
      { stat: 'resistance', bonus: 3 },
    ],
    rank: 3,
    weight: 1,
  },
  {
    id: 155,
    name: 'Cabasset à cornes',
    category: ArmorCategory.HELMET,
    bonuses: [
      { stat: 'armor', bonus: 3 },
      { stat: 'damage', bonus: 1 },
    ],
    rank: 3,
    weight: 2,
  },
  {
    id: 162,
    name: "Cagoule de l'ombre",
    category: ArmorCategory.HELMET,
    bonuses: [
      { stat: 'precision', bonus: 10 },
      { stat: 'stealth', bonus: 10 },
    ],
    rank: 3,
    weight: 1,
  },
  {
    id: 317,
    name: 'Capuche de rôdeur',
    category: ArmorCategory.HELMET,
    bonuses: [
      { stat: 'dexterity', bonus: 1 },
      { stat: 'stealth', bonus: 15 },
    ],
    rank: 3,
    weight: 1,
  },
  {
    id: 271,
    name: 'Capuchon en soie',
    category: ArmorCategory.HELMET,
    bonuses: [{ stat: 'resistance', bonus: 4 }],
    rank: 3,
    weight: 1,
  },
  {
    id: 291,
    name: 'Capuche féline',
    category: ArmorCategory.HELMET,
    bonuses: [
      { stat: 'evasion', bonus: 15 },
      { stat: 'intelligence', bonus: 1 },
    ],
    rank: 3,
    weight: 1,
  },
  {
    id: 86,
    name: 'Casque astral',
    category: ArmorCategory.HELMET,
    bonuses: [
      { stat: 'armor', bonus: 3 },
      { stat: 'dexterity', bonus: 1 },
    ],
    rank: 3,
    weight: 2,
  },
  {
    id: 137,
    name: 'Casque noble',
    category: ArmorCategory.HELMET,
    bonuses: [
      { stat: 'armor', bonus: 3 },
      { stat: 'intelligence', bonus: 1 },
    ],
    rank: 3,
    weight: 2,
  },
  {
    id: 194,
    name: 'Casque terrifiant',
    category: ArmorCategory.HELMET,
    bonuses: [
      { stat: 'armor', bonus: 3 },
      { stat: 'strength', bonus: 1 },
    ],
    rank: 3,
    weight: 2,
  },
  {
    id: 83,
    name: 'Chapeau du nomade',
    category: ArmorCategory.HELMET,
    bonuses: [
      { stat: 'luck', bonus: 50 },
      { stat: 'evasion', bonus: 5 },
      { stat: 'magicDefense', bonus: 5 },
    ],
    rank: 3,
    weight: 1,
  },
  {
    id: 25,
    name: 'Coiffe en soie',
    category: ArmorCategory.HELMET,
    bonuses: [
      { stat: 'magicDamage', bonus: 1 },
      { stat: 'resistance', bonus: 3 },
    ],
    rank: 3,
    weight: 1,
  },
  {
    id: 319,
    name: 'Crâne rituel',
    category: ArmorCategory.HELMET,
    bonuses: [
      { stat: 'spirit', bonus: 2 },
      { stat: 'magicDefense', bonus: 10 },
    ],
    rank: 3,
    weight: 2,
  },
  {
    id: 177,
    name: 'Diadème',
    category: ArmorCategory.HELMET,
    extraGem: true,
    bonuses: [
      { stat: 'intelligence', bonus: 1 },
      { stat: 'spirit', bonus: 1 },
      { stat: 'charisma', bonus: 1 },
    ],
    rank: 3,
    weight: 1,
  },
  {
    id: 11,
    name: 'Heaume',
    category: ArmorCategory.HELMET,
    bonuses: [{ stat: 'armor', bonus: 4 }],
    rank: 3,
    weight: 2,
  },
  {
    id: 329,
    name: 'Masque fantôme',
    category: ArmorCategory.HELMET,
    bonuses: [
      { stat: 'armor', bonus: 2 },
      { stat: 'stealth', bonus: 10 },
    ],
    rank: 3,
    weight: 2,
  },
];
